name: Docker Image CI - build and push pip-compile images for various python versions.

on:
  push:
    branches:
      - main
  schedule:
  - cron: '0 12 15 * *'

jobs:
  # Build for 3.8 to 3.12. https://devguide.python.org/versions/
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]  # , 3.9, 3.10, 3.11, 3.12
        include:
        - tag: alpine
          directory: alpine
#        - tag: slim-buster
#          directory: debian
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set date
      id: date
      run: echo "::set-output name=date::$(date --iso-8601=date)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build pip-compile images and push to docker
      uses: docker/build-push-action@v6
      with:
        tags: saurabheights/pip-compile:${{ matrix.python-version }}-${{ matrix.tag }}
        context: ./${{ matrix.directory }}
        build_args: TAG=${{ matrix.python-version }}-${{ matrix.tag }}
        labels: org.opencontainers.image.authors=khandujasaurabh@gmail.com,org.opencontainers.image.vendor=Saurabh Khanduja,org.opencontainers.image.licenses=Apache-2.0
        push: True
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

